### ISSUE TITLE
Better YT ID Regex

### ISSUE THREAD

**Issue by PlNG** [remarkablemark/youtube-video-id#5]
`[0-9A-Za-z_-]{10}[048AEIMQUYcgkosw]`
as seen here: https://webapps.stackexchange.com/a/101153

This might change should the length change, but this expression slightly increases the validation that it is a YT ID.

**Comment by remarkablemark** [comment]
Thanks for sharing this with me @PlNG

Would you like to have the honors of creating a pull request?

**Comment by remarkablemark** [comment]
No problem, thanks for creating the PR

I'll make a release some time later tonight

**Comment by remarkablemark** [comment]
v0.0.3 has been published:
```sh
# with npm
npm install --save youtube-video-id@0.0.3

# or with yarn
yarn add youtube-video-id@0.0.3
```
